#!/usr/bin/python3
"""module that factorize any number that can factorize as fas as posible"""
from sys import argv
from math import sqrt


def fac(value):
    """facterize every number that can be..."""
    i = 2

    if value < 2:
        return
    if value % 2 == 0:
        print("{:.0f}={:.0f}*{:.0f}".format(value, value / i, i))
        return
    sqn = int(sqrt(value))
    while sqn % 2 == 0:
        sqn += 1
    for j in range(3, sqn + 1, 2):
        if value % j == 0:
            print("{:.0f}={:.0f}*{:.0f}".format(value, value / j, j))
            break


if len(argv) != 2:
    exit()

try:
    with open(argv[1]) as files:
        line = files.readline()
        while line != "":
            value = int(line.split('\n')[0])
            fac(value)
            line = files.readline()
except Exception:
    pass
