#!/usr/bin/python3
"""module that factorize any number that can factorize as fas as posible"""
from sys import argv
from math import sqrt


def fac():
    """facterize every number that can be..."""
    if len(argv) != 2:
        exit()
    with open(argv[1]) as f:
        for line in f:
            if line != "\n":
                num = int(line)
                if num % 2 == 0:
                    print("{}={}*2".format(num, num // 2))
                    continue
                sqn = int(sqrt(num))
                while sqn % 2 == 0:
                    sqn += 1
                for i in range(3, sqn + 1, 2):
                    if num % i == 0:
                        print("{}={}*{}".format(num, num // i, i))
                        break
                if num % i != 0:
                    print("{}={}".format(num, num))


fac()
